To Do list: add & remove
VTY1999/To-Do-list pull request #2
Opened 2022-01-20 09:17 UTC by VTY1999

## To Do list: add & remove
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task.
- Implement a function for deleting a task.
- Implement a function for editing task descriptions.
- Implement local storage to save all changes.

2022-01-20 10:10 UTC, brytebee requested changes
Hi, @VTY1999 👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- good UI design✔️
- amazing implementation of unchanged event to edit item✔️
- items index update nicely✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-20 10:10 UTC, brytebee commented on README.md
>  ## Built With
- [ ] **Optional** The live demo link opens to your Readme file. Please fix this bug.

2022-01-20 10:10 UTC, brytebee commented on src/function.js
> +  const sortedTodos = listTask.list.sort((a, b) => a.index - b.index);
- [x] **Required:** When an item is removed from the end of the list, an item from the top is deleted instead because on reload, the last item return while the first is gone. This is abnormal behaviour and I think it has to do with sorting the data. Kindly consider using another approach to keep data sorted.

2022-01-20 10:10 UTC, brytebee commented on src/storage.js
> +  }
- [x] **Required:** I added a couple of items to the list and clicked the remove button, but the first click does not remove an item from the list. This is also abnormal. Kindly fix the bug.

**Hint:** Consider this function and the one you attached an event to

```
  const removeBtns = document.querySelectorAll('.remove');
  removeBtns.forEach((btn) => {
    btn.addEventListener('click', (e) => {
      const element = btn.parentNode;
      listTask.RemoveTask(Number(e.target.parentNode.id));
      element.remove();
    });
  });
```

2022-01-20 14:39 UTC, ShoiraTa requested changes
Hi @VTY1999 

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

- [ ] Sadly, the bugs mentioned by the previous reviewer are still there. More specifically: 
 - On the first click item is not removed from the local storage, on page reload it  gets back
 - When an item is removed from the end of the list, an item from the top is deleted instead because on reload, the last item return while the first is gone. 

- [ ] Please kindly resolve these issues. 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-20 20:15 UTC, brytebee requested changes
Hi, @VTY1999 👋, 

Great work on making the changes 👏 👏 
You've done well implementing some of the requested changes requested by the previous review, but there are still some which aren't addressed yet.


# Suggested changes
_Check the comments under the review._

![](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-20 20:15 UTC, brytebee commented on src/function.js
> +  });
- [ ] **Required:** This function still behave in an abnormal manner.
![localStorage not working](https://user-images.githubusercontent.com/27709832/150413633-ae848d7c-c0e9-4005-9f7c-05faf3f77464.gif)

Please fix this functionality by looking at all remove functionality as well as the how you get list items to display.

2022-01-25 10:48 UTC, brytebee approved these changes
Hi, @VTY1999 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-25 11:03 UTC, merged